name = "myip-worker"
main = "src/index.js"
compatibility_date = "2023-12-01"

# 自定义域名绑定
[[routes]]
pattern = "myip.sheepx.fun/*"
zone_name = "sheepx.fun"

[env.production]
name = "myip-worker"

# 生产环境自定义域名绑定
[[env.production.routes]]
pattern = "myip.sheepx.fun/*"
zone_name = "sheepx.fun"